"""Initial migration.

Revision ID: 4772cefc58d9
Revises: 680a10d8414e
Create Date: 2025-01-19 22:33:44.871353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4772cefc58d9'
down_revision = '680a10d8414e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('published_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('published_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
